title: 'Next.js 14 アプリ開発ガイド'
summary: 'Next.js 14 / Prisma / Clerk / Vercel Postgres / CloudFlare R2 / shadcn/ui / Tailwind CSS を使ったアプリ開発ガイド'
topics: ['nextjs', 'clerk', 'prisma', 'cloudflarer2']
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - intro
  - installation
  - init-clerk
  - init-cloudflare
  - init-vercel
  - init-prisma
  - layout
  - analytics
  - onboarding
  - file-tree-hint
  - post-list
  - post-detail
  - post-form
