title: 'Next.js 14 アプリ開発のあらすじ'
summary: 'Next.js 14 / Prisma / Clerk / Vercel Postgres / CloudFlare R2 / shadcn/ui / Tailwind CSS を使ったアプリ開発の雰囲気をつかむ'
topics: ['nextjs', 'clerk', 'prisma', 'cloudflarer2', 'bun']
published: true
price: 0
chapters:
  - intro
  - installation
  - init-clerk
  - init-cloudflare
  - init-vercel
  - init-prisma
  - layout
  - onboarding
  - post-list
  - post-detail
  - post-form
  - not-found
  - analytics
  - favicon
  - meta
  - file-tree-hint
  - cache
  - tools
  - advanced-router
  - form-error-handling
